// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xcpc.proto

package xcpctx

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type XCPCsend struct {
	Asset                string   `protobuf:"bytes,1,opt,name=asset" json:"asset,omitempty"`
	Quantity             uint64   `protobuf:"varint,2,opt,name=quantity" json:"quantity,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	Memo                 string   `protobuf:"bytes,4,opt,name=memo" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XCPCsend) Reset()         { *m = XCPCsend{} }
func (m *XCPCsend) String() string { return proto.CompactTextString(m) }
func (*XCPCsend) ProtoMessage()    {}
func (*XCPCsend) Descriptor() ([]byte, []int) {
	return fileDescriptor_xcpc_d6e187559db5d77d, []int{0}
}
func (m *XCPCsend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XCPCsend.Unmarshal(m, b)
}
func (m *XCPCsend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XCPCsend.Marshal(b, m, deterministic)
}
func (dst *XCPCsend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XCPCsend.Merge(dst, src)
}
func (m *XCPCsend) XXX_Size() int {
	return xxx_messageInfo_XCPCsend.Size(m)
}
func (m *XCPCsend) XXX_DiscardUnknown() {
	xxx_messageInfo_XCPCsend.DiscardUnknown(m)
}

var xxx_messageInfo_XCPCsend proto.InternalMessageInfo

func (m *XCPCsend) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *XCPCsend) GetQuantity() uint64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *XCPCsend) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *XCPCsend) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func init() {
	proto.RegisterType((*XCPCsend)(nil), "xcpctx.XCPCsend")
}

func init() { proto.RegisterFile("xcpc.proto", fileDescriptor_xcpc_d6e187559db5d77d) }

var fileDescriptor_xcpc_d6e187559db5d77d = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xaa, 0x48, 0x2e, 0x48,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0xb1, 0x4b, 0x2a, 0x94, 0xb2, 0xb8, 0x38,
	0x22, 0x9c, 0x03, 0x9c, 0x8b, 0x53, 0xf3, 0x52, 0x84, 0x44, 0xb8, 0x58, 0x13, 0x8b, 0x8b, 0x53,
	0x4b, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x29, 0x2e, 0x8e, 0xc2, 0xd2,
	0xc4, 0xbc, 0x92, 0xcc, 0x92, 0x4a, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x96, 0x20, 0x38, 0x5f, 0x48,
	0x82, 0x8b, 0x3d, 0x31, 0x25, 0xa5, 0x28, 0xb5, 0xb8, 0x58, 0x82, 0x19, 0xac, 0x07, 0xc6, 0x15,
	0x12, 0xe2, 0x62, 0xc9, 0x4d, 0xcd, 0xcd, 0x97, 0x60, 0x01, 0x0b, 0x83, 0xd9, 0x49, 0x6c, 0x60,
	0xab, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x7e, 0x99, 0xf0, 0x88, 0x00, 0x00, 0x00,
}
